version: '2'
services:
    web:
        build: .
        command: npm start
        volumes:
            - .:/usr/app/
            - /usr/app/node_modules
        ports:
            - "3000:3000"
        depends_on:
            - postgres
        environment:
            DATABASE_URL: postgres://postgres:1234@postgres/saamaanwala
    postgres:
        image: postgres
        environment:
            POSTGRES_USER: postgres
            POSTGRES_DB: saamaanwala
            POSTGRES_PASSWORD: 1234